### PR TITLE
WIP: Merge Amundsen metadata and search repositories in to a single `amundsenbackend` repository

### PR DESCRIPTION
**Pull request by verdan**
Signed-off-by: verdan <verdan.mahmood@gmail.com>

The idea is to deprecate the split of metadata and search repositories and merge them into a single `amundsenbackend` repository.

### CODE REVIEW

**Comment by Golodhros** [comment]
I think this RFC proposal reinforces the idea that we are having difficulties with the current split of our repos and the sluggish workflow we need to follow in order to fix even the smallest thing.

In this sense, I agree with @Dorianj that the best first step would be to move into a monorepo, as he details on [this comment](https://github.com/amundsen-io/rfcs/pull/15#issuecomment-733289622).

**Comment by feng-tao** [comment]
I will take a look at the comment but a few things for mono repos:
1. how do we make sure backward compatibility ? 
2. Users have lots of custom endpoint API in metadata/search (e.g  Lyft)? Are we able to grow metadata to a standalone API server still?
This is a key as not everyone uses Amundsen purely through UI but leverage service level integration.
3. How we do release? Having separate repos certainly do have challenges with integration but it allows something like what we did (gremlin repo, rds repo) instead of make the mono repo a kitchen sink.

**Comment by verdan** [comment]
this is a WIP :thought_balloon:. I will complete the transition path, along with technical details, code splits, and even code structure on the modular level soon. This change will indeed need changes in the CI/CD pipelines and docker files but eventually would not affect much on the frontend-backend integration.

**Comment by verdan** [comment]
Closed in favour of https://github.com/amundsen-io/rfcs/pull/30

**Pull request closed without merging**
